fix: latest_commit_timestamp output

diff --git a/.github/workflows/pr-actuality-check.yml b/.github/workflows/pr-actuality-check.yml
--- a/.github/workflows/pr-actuality-check.yml
+++ b/.github/workflows/pr-actuality-check.yml
@@ -54,7 +54,14 @@ jobs:
           fetch-depth: 0
       - id: latest-commit
         name: Get latest commit timestamp
-        run: echo "latest_commit_timestamp=$(git log --no-merges --grep ${{ needs.prepare.outputs.translation }} --format=%ct -1)"
+        run: |
+          latest_commit_timestamp=$(git log --no-merges --grep ${{ needs.prepare.outputs.translation }} --format=%ct -1)
+          if [ -z "$latest_commit_timestamp" ]; then
+            echo 'Failed to find latest commit timestamp'
+            exit 1
+          else
+            echo "latest_commit_timestamp=$latest_commit_timestamp" >> $GITHUB_OUTPUT
+          fi
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
@@ -65,7 +72,7 @@ jobs:
         run: |
           cd original
           # Get commits after ${{ steps.latest-commit.outputs.latest_commit_timestamp }} timestamp
-          git log --format=%H --since="${{ steps.latest-commit.outputs.latest_commit_timestamp }}" > ../fresh_commits.txt
+          git log --format=%H --since=${{ steps.latest-commit.outputs.latest_commit_timestamp }} > ../fresh_commits.txt
           cat ../fresh_commits.txt
           # has_fresh_commits is true when there are fresh commits, otherwise false
           if [ -s ../fresh_commits.txt ]; then
