feature: reviewdog

diff --git a/.github/workflows/spellcheck.yml b/.github/workflows/spellcheck.yml
--- a/.github/workflows/spellcheck.yml
+++ b/.github/workflows/spellcheck.yml
@@ -98,15 +98,23 @@ jobs:
         run: |
           cat uk_spelling_additions.txt >> ./LanguageTool-6.3/org/languagetool/resource/uk/hunspell/spelling.txt
           cat uk_ignore_additions.txt >> ./LanguageTool-6.3/org/languagetool/resource/uk/hunspell/ignore.txt
-      - name: Check spelling
+      - id: check-spelling
+        name: Check spelling
         run: |
           disabled_rules=$(cat disabled_rules.txt | tr '\n' ',')
           cd LanguageTool-6.3
           result=$(java -jar languagetool-commandline.jar -d ${disabled_rules} -l uk --json ../${{ steps.md2txt.outputs.translation }})
-          if [ "$result" == "[]" ]; then
-            echo "No spelling errors found"
-          else
-            echo "Spelling errors found"
-            echo $result
-            exit 1
-          fi
+          result=$(echo $result | jq '.matches')
+          echo "result=$result" >> $GITHUB_OUTPUT
+      - if: steps.check-spelling.outputs.result != '[]'
+        name: Check spelling
+        run: echo "Spelling errors found" && echo ${{ steps.check-spelling.outputs.result }} && exit 1
+      - if: steps.check-spelling.outputs.result != '[]'
+        name: Install reviewdog
+        run: wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s [vX.Y.Z]
+      - if: steps.check-spelling.outputs.result != '[]'
+        name: Send results
+        run: |
+          message=$(echo "${{ steps.check-spelling.outputs.result }}" | tmpl ./langtool.tmpl)
+          export REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}
+          echo $message | reviewdog -efm="%A%f:%l:%c: %m" -efm="%C %m" -name="LanguageTool" -level=info
